# Generated by Django 5.1.7 on 2025-05-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cor',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
